### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by rvahaver** [Nauplius/AWACPM#1]
First of all Trevor I wanted to let you know how much I like this and will recommend it to all of my clients.  We just need to update some documentation to help those that are not familiar with your code/process.

The ReadMe.md talks about the -ConfigurationFile C:\WACConfiguration but does not explain what it is or how to go about creating one if you don't have it.  Is it just a location to store configuration data or what?

The same thing holds true for -SetAsLeadHost $true.  What do you mean when you say that.  Is it the first server that you added to SharePoint when you did the spwopibinding?

Great Job on this!
David

**Comment by tseward** [comment]
Added what the parameters do to the readme. Will move to the wiki as time permits.
