### ISSUE TITLE
Machine roles are not getting applied for new lead host

### ISSUE THREAD

**Issue by egor-yudkin** [Nauplius/AWACPM#3]
If you have customized roles for the machine which will become a new lead host (i.e. the first machine you patch), these roles are not going to be applied by the script. Instead, this machine will have "All" roles set.

**Comment by tseward** [comment]
Thanks for reporting it, I'll see what I can do.

**Comment by egor-yudkin** [comment]
Looks like line 180 needs to be changed from
`Get-MachineXml`
to
`$machine = Get-MachineXml`

I submitted the pull request for that: #5

**Comment by tseward** [comment]
PR comitted.
